### ISSUE TITLE
Custom node differentiator missing

### ISSUE THREAD

**Issue by Lazarica-t** [johnpierson/MonocleForDynamo#15]
Does Dynamo 2.6 not support this feature? or why was "Custom node differentiator" removed, it was very handy

**Describe the bug**
Custom node differentiator missing
![image](https://user-images.githubusercontent.com/49474519/100243804-f338dd00-2f3e-11eb-9415-2f528626d455.png)

**Expected behavior**
Custom node differentiator should appear in the drop down menu

**My setup**
- Operating System: Win10 20H2
- Dynamo version: 2.6.1
- Monocle version: 2020.10.1
- Revit version: 2021.1.1

**Comment by johnpierson** [comment]
Hey there @Lazarica-t! That tool was removed as it was a little unstable in the way it was coloring. If you had a large graph it would iterate through all the nodes because the Dynamo team offers no way to get the view of the node from the actual element.

I will look at reintroducing it, but with some of the [other](https://github.com/johnpierson/MonocleForDynamo/issues/2) updates we had, that one made sense to get rid of for now.

**Comment by Lazarica-t** [comment]
@johnpierson Thank you for the answer.
Well I hope it gets integrated back, I find it very useful to quickly identify custom nodes from other packages without having to use the doge tool (very handy when opening graphs from other users or pre-monocle created graphs :)) when I was not aware on the doge tool).

**Comment by johnpierson** [comment]
This is now in version 2021.5.1 in a different way. it will highlight currently placed nodes with a green dotted outline.

The previous implementation was too resource-heavy to do as you worked. this does it on-demand now

**Comment by Lazarica-t** [comment]
Cool, I've been using this lately to update some of my old scripts. Is there any way of making the highlight pop-out more? 😄 Green is nice and all, but not that visible when you are zoomed out, maybe a more vibrant color? and thicker lines 😉 

Would be a great addition for future releases 👍
