### ISSUE TITLE
Control over custom node highlight

### ISSUE THREAD

**Issue by aussieBIMguru** [johnpierson/MonocleForDynamo#7]
**What is the problem that needs solving?**
Current node colour for custom node headers appears to be set to one option. Default inactive node constrast is hard on the eyes (black on dark blue).

**How would you like to see it solved?**
Preferences menu added where user can specify the active/inactive node header text and fill colours.

**Describe alternatives you've considered**
Iris

![drake issue](https://user-images.githubusercontent.com/58870499/84336546-d4d26580-abda-11ea-88f3-8e1084986a78.png)

**Comment by johnpierson** [comment]
This one is interesting because those font colors are controlled via Dynamo. In your example, the white one has no inputs. Resulting in it being fulfilled and being white. The other example is lacking inputs and is not fulfilled resulting in the black text. 

Right off hand, I don't think I can control that _easily_, but I will dig some more or consider other ways of "highlighting" custom nodes.

**Comment by johnpierson** [comment]
Closing this as the custom node coloring is being removed from Monocle.
